version: "3"
services:

  partkeepr:
    image: mhubig/partkeepr:1.4.0-11
    environment:
      - PARTKEEPR_DATABASE_HOST=database
      - PARTKEEPR_DATABASE_NAME=partkeepr
      - PARTKEEPR_DATABASE_PORT=3306
      - PARTKEEPR_DATABASE_USER=partkeepr
      - PARTKEEPR_DATABASE_PASS=partkeepr
      - PARTKEEPR_OKTOPART_APIKEY
    ports:
      - "80:80"
    volumes:
      - partkeepr-data:/var/www/html/data
      - partkeepr-web:/var/www/html/web
    depends_on:
      - database

  database:
    image: mariadb:10.3
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  partkeepr-data:
  partkeepr-web:
  mysql-data:
