version: "3"
services:

  partkeepr:
    image: mhubig/partkeepr:1.4.0-9
    environment:
      - PARTKEEPR_DATABASE_HOST=database  # not used for now
      - PARTKEEPR_DATABASE_NAME=partkeepr # not used for now
      - PARTKEEPR_DATABASE_PORT=3306      # not used for now
      - PARTKEEPR_DATABASE_USER=partkeepr # not used for now
      - PARTKEEPR_DATABASE_PASS=partkeepr # not used for now
      - PARTKEEPR_OKTOPART_APIKEY=0123456 # not used for now
    ports:
      - "80:80"
    volumes:
      - partkeepr-data:/var/www/html/data
    depends_on:
      - database

  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  partkeepr-data:
  mysql-data:
