version: "3"
services:

  database:
    image: mariadb:10.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysql-data:/var/lib/mysql

  partkeepr:
    image: mhubig/partkeepr:latest
    environment:
      - PARTKEEPR_DATABASE_HOST
      - PARTKEEPR_DATABASE_NAME
      - PARTKEEPR_DATABASE_PORT
      - PARTKEEPR_DATABASE_USER
      - PARTKEEPR_DATABASE_PASS
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTCANONICALFORM
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTDOMAINNAME
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTDOMAINNAMESHORT
      - PARTKEEPR_FR3D_LDAP_DRIVER_ACCOUNTFILTERFORMAT
      - PARTKEEPR_FR3D_LDAP_DRIVER_BASEDN
      - PARTKEEPR_FR3D_LDAP_DRIVER_BINDREQUIRESDN
      - PARTKEEPR_FR3D_LDAP_DRIVER_HOST
      - PARTKEEPR_FR3D_LDAP_DRIVER_OPTREFERRALS
      - PARTKEEPR_FR3D_LDAP_DRIVER_PASSWORD
      - PARTKEEPR_FR3D_LDAP_DRIVER_PORT
      - PARTKEEPR_FR3D_LDAP_DRIVER_USESSL
      - PARTKEEPR_FR3D_LDAP_DRIVER_USESTARTTLS
      - PARTKEEPR_FR3D_LDAP_DRIVER_USERNAME
      - PARTKEEPR_FR3D_LDAP_USER_ATTRIBUTE_EMAIL
      - PARTKEEPR_FR3D_LDAP_USER_ATTRIBUTE_USERNAME
      - PARTKEEPR_FR3D_LDAP_USER_BASEDN
      - PARTKEEPR_FR3D_LDAP_USER_ENABLED
      - PARTKEEPR_FR3D_LDAP_USER_FILTER
      - PARTKEEPR_LOCALE
      - PARTKEEPR_MAILER_AUTH_MODE
      - PARTKEEPR_MAILER_ENCRYPTION
      - PARTKEEPR_MAILER_HOST
      - PARTKEEPR_MAILER_PASSWORD
      - PARTKEEPR_MAILER_PORT
      - PARTKEEPR_MAILER_TRANSPORT
      - PARTKEEPR_MAILER_USER
      - PARTKEEPR_AUTH_MAX_USERS
      - PARTKEEPR_CATEGORY_PATH_SEPARATOR
      - PARTKEEPR_CRONJOB_CHECK
      - PARTKEEPR_FILESYSTEM_DATA_DIRECTORY
      - PARTKEEPR_FILESYSTEM_QUOTA
      - PARTKEEPR_MAINTENANCE
      - PARTKEEPR_MAINTENANCE_MESSAGE
      - PARTKEEPR_MAINTENANCE_TITLE
      - PARTKEEPR_OCTOPART_APIKEY
      - PARTKEEPR_PARTS_INTERNALPARTNUMBERUNIQUE
      - PARTKEEPR_PARTS_LIMIT
      - PARTKEEPR_USERS_LIMIT
      - PARTKEEPR_SECRET
    ports:
      - "8080:80"
    volumes:
      - partkeepr-conf:/var/www/html/app/config
      - partkeepr-data:/var/www/html/data
      - partkeepr-web:/var/www/html/web
    depends_on:
      - database

  cronjob:
    image: mhubig/partkeepr:latest
    entrypoint: []
    command: bash -c "crontab /etc/cron.d/partkeepr && cron -f"
    volumes:
      - partkeepr-conf:/var/www/html/app/config:ro
      - partkeepr-data:/var/www/html/data
      - partkeepr-web:/var/www/html/web
    depends_on:
      - partkeepr

volumes:
  partkeepr-conf:
  partkeepr-data:
  partkeepr-web:
  mysql-data:
